name: "C++ CI build"
run-name: ${{ github.actor }} executed build ${{ inputs.testname }}

on:
  workflow_dispatch:
    inputs:
      testname:
        default: "manually"
        description: "build title"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: updata package database
      run: sudo apt-get update
    - name: update gcc
      run: |
        sudo apt-get upgrade gcc
    - name: check gcc version
      run: gcc -v
    - name: submodules
      run: git submodule update --init --recursive --remote
    - name: make
      run: make
